### PR TITLE
NODE-2431: Reduce floating point precision required of extended json implementations

### PR DESCRIPTION
**Pull request by nbbeeken**
Port of https://github.com/mongodb/js-bson/pull/369

### CODE REVIEW

**Review by emadum — APPROVED** [review]
LGTM 👍

**Review by mbroadst — APPROVED** [review]
LGTM, but what's going on with the build failure in Travis?

**Comment by nbbeeken** [comment]
> LGTM, but what's going on with the build failure in Travis?

Good question I actually have to rebase this change onto the 3.0 branch so that might pass the build fine, but it looks like the commits since 3.0 on master have introduced an update to 'buffer' that changed the import syntax. There are in fact breaking changes in master that we can't put into 3.0 so our plan to drop simply drop the 4.0 track isn't so straight forward.

**Comment by nbbeeken** [comment]
I updated the driver we test against to 3.5 since that's the minimum version we support that also uses this ext-json lib. This also brings over commits that are published under the major ver 3 for this lib just to keep the `3.0` branch up to date. you should be able to to use the commit filter to view only the changes I've made since `3.0.3`

**Review by mbroadst — APPROVED** [review]
:+1: thanks for the update, LGTM!

**Pull request merged**
